// ==========================================================================
// 5 IN 5 - SOLUZIONI GIORNALIERE E GENERATORE PUZZLE (words.js)
// ==========================================================================

const WORDS_POOL_4 = [
  "ALBA", "ALTO", "ALCE", "ANNO", "ANZI", "APRI", "ARCO", "AREA", "ARIA", "ARMA", "ARTE",
  "ASTA", "ATTO", "AULA", "AUTO", "BACI", "BACO", "BAIA", "BASE", "BASI", "BENE",
  "BENI", "BERE", "BICI", "BUCA", "BUCO", "BUIO", "BUOI", "CANE", "CAPO", "CARA",
  "CARE", "CARI", "CARO", "CASA", "CASE", "CASI", "CASO", "CAVI", "CAVO", "CECI",
  "CENA", "CENE", "CERA", "CIBO", "CIMA", "CLAN", "CLUB", "CODA", "COME", "CONO",
  "CORO", "COSA", "COSE", "CUBO", "CURA", "CURE", "DADI",
  "DADO", "DAMA", "DARE", "DATI", "DATO", "DEVE", "DIGA", "DIRE", "DITA", "DITO",
  "DONI", "DONO", "DOPO", "DOSE", "DOTE", "DOVE", "DUCA", "DUCE", "DURO", "ECCO",
  "EGLI", "ELFO", "ELMO", "ENTE", "ERBA", "EROE", "ESSA", "ESSI", "ESSO", "EURO",
  "FAME", "FARE", "FARO", "FATO", "FAVA", "FEDE", "FICO", "FIDO", "FILA", "FILE",
  "FILI", "FILM", "FILO", "FINE", "FINO", "FOCA", "FOCE", "FOTO", "FUGA", "FUMO",
  "FUNE", "GALA", "GARA", "GARE", "GELO", "GIRO", "GITA", "GOLA", "GUAI", "GUFO",
  "IDEA", "IDEE", "IENA", "IERI", "INNO", "IRIS", "JAZZ", "JEEP", "JUDO", "LAGO",
  "LAMA", "LANA", "LATO", "LAVA", "LEGA", "LEGO", "LEVA", "LIRA", "LORO", "LUCE",
  "LUCI", "LUNA", "LUPO", "MAGO", "MALE", "MANI", "MANO", "MARE", "MELA", "MENO",
  "MESE", "META", "MICA", "MINA", "MIRA", "MODO", "MOTO", "MURI", "MURO",
  "NASO", "NAVE", "NERO", "NEVE", "NIDO", "NODO", "NOME", "NORD", "NOTA", "NOTE",
  "NOTO", "NOVE", "NUDE", "NUDO", "OGGI", "OGNI", "OLIO", "OLMO", "ONDA", "ONDE", "ORSO",
  "ORTO", "ORLO", "OTTO", "PACE", "PAGA", "PANE", "PENA", "PERA", "PESO",
  "PINO", "PIPA", "POCO", "PURE", "PURO", "RAMO", "RANA", "RAVE", "RETE", "RISO",
  "RIVA", "ROBA", "ROSA", "ROSE", "SALA", "SALE", "SEDE", "SERA", "SETA", "SINO",
  "SOFA", "SOLE", "SOLO", "TALE", "TANA", "TELA", "TEMA", "TEST", "TIPO", "TOGA",
  "TONO", "TUBO", "UOMO", "VANO", "VELA", "VERO", "VINO", "VISO", "VITA", "VIVO",
  "VOCE", "VOLO", "ZONA"
];

const WORDS_POOL_5 = [
  "ABETE", "ABITI", "ABITO", "ACETO", "ACIDO", "ACQUA", "ACUTO", "AEREO", "AGILE", "AGLIO",
  "AIUTO", "ALBUM", "ALICE", "ALTRO", "AMARE", "AMARO", "AMICA", "AMICI", "AMICO", "AMIDO",
  "AMORE", "AMPIO", "ANCHE", "ANIMA", "ANIMO", "ANSIA", "ANTRO", "APICE", "ARABO", "ARENA",
  "AROMA", "ASILO", "ASINO", "ASPRO", "ASSAI", "ASTRO", "ATOMO", "ATRIO", "AUDIO", "AVARO",
  "AVENA", "AVERE", "AVIDO", "AVVIO", "AZOTO", "BACCA", "BACIO", "BAFFO", "BAGNO", "BAITA",
  "BALDO", "BALLO", "BALZO", "BANCA", "BANCO", "BANDA", "BARBA", "BARCA", "BARRA", "BASSO",
  "BASTA", "BEATO", "BELLA", "BELLO", "BENDA", "BIRRA", "BIVIO", "BOCCA", "BOLLO",
  "BOMBA", "BORDO", "BORGO", "BORSA", "BOSCO", "BOTTA", "BOTTE", "BRAVO", "BREVE", "BRINA",
  "BRODO", "BRUNO", "BUONO", "BURRO", "BUSTA", "BUSTO", "CALDO", "CALMA", "CALZA",
  "CAMPO", "CANTO", "CAPRA", "CARNE", "CARTA", "CASSA", "CAUSA", "CENTO", "CERTO", "CERVO",
  "CHILO", "CHINA", "CIELO", "CIRCA", "CIRCO", "CLIMA", "COBRA", "COLLE", "COLLO",
  "COLPA", "COLPO", "CONTO", "CORDA", "CORNO", "CORPO", "CORSA", "CORSO", "CORTO", "COSTA",
  "COSTO", "COZZA", "CREDO", "CRISI", "CROCE", "CUORE", "CURVA", "DENTE", "DIECI", "DISCO", "DOLCE",
  "DONNA", "DORSO", "DRAMA", "ELICA", "ENTRO", "EPOCA", "ESAME", "FALCO", "FANGO",
  "FARRO", "FATTO", "FERMO", "FERRO", "FESTA", "FIORE", "FIUME", "FOLLA", "FONDO", "FONTE",
  "FORMA", "FORNO", "FORSE", "FORTE", "FORZA", "FOSSO", "FRASE", "FRENO", "FRODE", "FUOCO",
  "FUORI", "FURTO", "GAMBA", "GATTO", "GENTE", "GESSO", "GESTO", "GIOCO", "GIOIA", "GLOBO",
  "GOLFO", "GOMMA", "GONNA", "GRADO", "GRANO", "GRATO", "GRAVE", "GRECO", "GUSTO", "HOTEL",
  "ISOLA", "LAMPO", "LARGO", "LATTE", "LEGGE", "LEGNO", "LENTO", "LEONE", "LETTO", "LIBRO",
  "LINEA", "LOTTA", "LUNGO", "LUOGO", "MADRE", "MAGIA", "MAMMA", "MANTO", "MARCA", "MASSA",
  "MEDIO", "MENTE", "MERLO", "MESSA", "METRO", "MEZZO", "MOLTO", "MONDO", "MONTE", "MORTE",
  "MOTTO", "MUCCA", "NOTTE", "NULLA", "NUOVO", "ODORE", "OLTRE", "OMBRA", "ONORE", "OPERA",
  "PADRE", "PAESE", "PALCO", "PARCO", "PARTE", "PASSO", "PASTA", "PAURA", "PAZZO", "PELLE",
  "PEZZO", "PIANO", "PIEDE", "PIENO", "POETA", "PONTE", "PORRE", "PORTA", "PORTO",
  "POSTO", "PRATO", "PRIMA", "PRIMO", "PROVA", "PUNTA", "PUNTO", "QUALE", "QUASI", "RADIO",
  "REALE", "REGNO", "RESTO", "RICCO", "ROSAI", "ROSSO", "RUOTA", "RUSSO", "SACRO", "SASSO",
  "SCALA", "SCENA", "SCOPO", "SEGNO", "SENSO", "SENZA", "SERIE", "SERIO", "SETTE", "SOGNO", "SONNO",
  "SOPRA", "SOTTO", "SPADA", "SPESA", "STARE", "STATO", "TANTO", "TARDI", "TASCA", "TEMPO",
  "TERZO", "TESTA", "TRENO", "TUTTO", "UDIRE", "UMANO", "UNICO", "UNIRE", "USARE", "UTILE",
  "VALLE", "VARIO", "VASTO", "VENTO", "VERDE", "VERSO", "VILLA", "VISTA", "VOLTA", "VOLTO",
  "VUOTO", "ZITTO", "ZORRO"
];

const WORDS_POOL_6 = [
  "ABBACO", "ABISSO", "ACCADE", "ACCESO", "ACCUSA", "ACERBO", "ADATTO", "ADESSO", "ADORNO", "ADULTO",
  "AFFARE", "AFFARI", "AFFINE", "AGENTE", "AGOSTO", "AGRUMI", "AIRONE", "AIUOLA", "ALBERO", "ALBUME",
  "ALCUNI", "ALCUNO", "ALLORA", "ALLORO", "ALMENO", "ALPINO", "ALTERO", "ALTRUI", "ALZARE", "AMANTE",
  "AMBITO", "AMORFO", "ANCORA", "ANDARE", "ANELLO", "ANGELO", "ANGOLO", "ANNATA", "ANTICO", "APERTO",
  "APOLLO", "APPENA", "APPESO", "APRILE", "APRIRE", "AQUILA", "ARANCI", "ARAZZO", "ARCATA", "ARDITO",
  "ARGINE", "ARMARE", "ARMATA", "ARREDO", "ARTICO", "ASCESA", "ASPIDE", "ASSALE", "ASTUTO", "ATLETA",
  "ATTESA", "ATTIMO", "ATTIVO", "ATTORE", "AUGURI", "AURORA", "AUTORE", "AVANTI", "AVANZI", "AVARIA",
  "AVVISO", "AZIONE", "AZTECO", "BACINO", "BADARE", "BADILE", "BALENA", "BANANA", "BANCHE", "BARILE",
  "BARONE", "BESTIA", "BEVUTA", "BIANCO", "BIBBIA", "BINARI", "BIONDO", "BLOCCO", "BOCCIA", "BOTOLA",
  "BOVINO", "BRACCI", "BRANCO", "BREZZA", "BRONZO", "BRULLO", "BRUTTO", "BUFALO", "BUFERA", "CABINA",
  "CADERE", "CALCIO", "CAMERA", "CAMINO", "CANALE", "CANORO", "CAPACE", "CAPIRE", "CASALE", "CASINO",
  "CATENA", "CATINO", "CEDOLA", "CELERE", "CENERE", "CENTRO", "CHIARO", "CHIAVE", "CHIESA", "CHIODO",
  "CICALA", "CIMICE", "CINQUE", "CINEMA", "CIPRIA", "CIVILE", "CLASSE", "CODICE", "COFANO", "COLERA", "COLORE",
  "COLORO", "COMETA", "COMODO", "COMUNE", "CONCIO", "CONTRO", "CORONA", "COTONE", "CREARE", "CUCINA",
  "CUGINO", "CUPOLA", "DATORE", "DEBITO", "DECIMO", "DENARO", "DENTRO", "DESTRO", "DIETRO",
  "DIFESA", "DIVANO", "DOCCIA", "DOGANA", "DOLORE", "DOMANI", "DONATO", "DOPPIO", "DOVERE", "DUBBIO",
  "DUNQUE", "DURARE", "EGITTO", "ENORME", "EPPURE", "ERRORE", "ESATTA", "ESATTO", "ESSERE", "ESTATE",
  "ESTERO", "FACCIA", "FACILE", "FAMOSO", "FARINA", "FASCIA", "FATICA", "FAVOLA", "FAVORE", "FEDELE",
  "FELICE", "FERIRE", "FERITA", "FIAMMA", "FIANCO", "FIGLIA", "FIGLIO", "FIGURA", "FILONE",
  "FINIRE", "FOGLIA", "FOGLIO", "FRANCO", "FREDDO", "FRESCO", "FRETTA", "FRONTE", "FRUTTO", "FUMARE",
  "FUTURO", "GABBIA", "GELATO", "GENERE", "GIALLO", "GIORNO", "GIRARE", "GIUGNO", "GIUSTO", "GODERE",
  "GRANDE", "GRAZIA", "GRAZIE", "GREMBO", "GRIGIO", "GROSSO", "GROTTA", "GRUPPO", "GUANTO", "GUERRA",
  "IDIOMA", "IGNOTO", "IMBUTO", "INCISO", "INDOLE", "INFAME", "INFINE", "INIZIO", "INTERO", "INVECE",
  "LABBRO", "LANCIA", "LATINO", "LAVORO", "LEGARE", "LEVARE", "LIBERO", "LIMITE", "LIMITI", "LINGUA",
  "LUCIDO", "MADAMA", "MAGARI", "MAGGIO", "MAGLIA", "MANICA", "MARINA", "MARITO", "MEDICO", "MEGLIO",
  "MENTRE", "MERITO", "MINIMO", "MINORE", "MINUTO", "MISURA", "MOGLIE", "MORALE", "MORIRE", "MOTIVO",
  "MOTORE", "MUSICA", "NATURA", "NEMICO", "NIENTE", "NOBILE", "NOSTRO", "NOTARE", "NOTIZIA", "NUMERO",
  "NUVOLE", "OCCHIO", "OGNUNO", "ONESTO", "OPPURE", "ORAMAI", "ORDINE", "OTTICO", "PAGARE", "PAGINA",
  "PARERE", "PARETE", "PAROLA", "PATRIA", "PAVONE", "PEGGIO", "PESARE", "PIANTA", "PIAZZA",
  "PIETRA", "POESIA", "POPOLO", "POSARE", "POTERE", "POVERO", "PRANZO", "PRESSO", "PRESTO", "PREZZO",
  "PRONTO", "QUADRO", "QUANTO", "QUARTO", "QUELLO", "QUESTO", "QUINDI", "RAPIDO", "RECARE",
  "REGALO", "RIDERE", "ROMANO", "RUMORE", "SABBIA", "SALIRE", "SALUTE", "SANGUE", "SAPERE", "SCARPA",
  "SCUOLA", "SECOLO", "SEDERE", "SERENO", "SFORZO", "SICURO", "SIMILE", "SOLITO", "SPALLA", "SPAZIO",
  "SPECIE", "SPESSO", "STAMPA", "STANCO", "STANZA", "STELLA", "STESSO", "STORIA", "STRADA", "STRANO",
  "STUDIO", "SUBITO", "TACERE", "TAVOLA", "TAVOLO", "TEATRO", "TEMERE", "TENERE", "TESORO", "TIRARE",
  "TITOLO", "TRARRE", "TRATTO", "TRISTE", "TROPPO", "UGUALE", "ULTIMO", "USANZA", "USCIRE", "VALERE",
  "VALORE", "VEDERE", "VELENO", "VENIRE", "VIAGGI", "VICINO", "VISITA", "VIVERE", "VOGLIA", "VOLARE",
  "VOLERE", "VOSTRO", "ZUCCHE"
];

const WORDS_POOL_7 = [
  "ABBATTE", "ABBAZIA", "ABBONDA", "ABITARE", "ACCANTO", "ACCENTO", "ACCETTA", "ACCIAIO", "ACCIUGA", "ACCOLTA",
  "ACCORDO", "ACCORTO", "ADDOSSO", "ADESIVO", "ADIRATO", "ADORATA", "ADORATO", "AFFATTO", "AFFETTO", "AFFITTO",
  "AFFLATO", "AGGETTO", "AGNELLI", "AIUTARE", "ALBERGO", "ALBERTO", "ALLERTA", "ALLERTE", "ALLOGGI",
  "ALLUNGA", "ALTERNO", "ALVEARE", "AMABILE", "AMARENA", "AMBIGUO", "ANALISI", "ANALOGO", "ANANAS", "ANATEMA", "ANDANTE",
  "ANIMALE", "ANIMATO", "ANNUALE", "ANNUNCI", "ANTENNA", "ANTICHI", "APATICO", "APICALE", "APPALTO", "APPARSO",
  "APPELLO", "APPORTO", "APPRODO", "APPUNTO", "ARANCIO", "ARATORE", "ARBITRO", "ARBUSTO", "ARCHIVI", "ARDENTE",
  "ARDUITA", "ARGENTO", "ARGILLA", "ARMONIA", "ARRESTO", "ARTISTA", "ASCIUGA", "ASCOLTO", "ASFALTO", "ASPETTO",
  "ASSALTO", "ASSEDIO", "ASSETTO", "ASSIOMA", "ASSISTE", "ASSOLTO", "ASSURDO", "ATLANTE", "ATTACCO", "ATTENTO",
  "ATTINTO", "ATTORNO", "ATTUALE", "AUSILIO", "AUTISMO", "AUTISTA", "AUTOBUS", "AUTUNNO", "AVVENTO", "AVVERTO",
  "AVVIATO", "AZIENDA", "AZZARDO", "AZZURRO", "BACIARE", "BAGAGLI", "BALSAMO", "BAMBINA", "BAMBINO", "BARATRO",
  "BASCULA", "BASTARE", "BASTONE", "BATTERE", "BATTERI", "BATTITO", "BENIGNO", "BENZINA", "BIBLICO", "BIDENTE",
  "BINARIO", "BISESTO", "BISOGNO", "BOCCALE", "BORDATA", "BOSCOSO", "BOTTONE", "BRACCIO", "BUTTARE", "CADENZA",
  "CAMELIA", "CAMICIA", "CAMPANA", "CAMPATA", "CANTARE", "CANTINA", "CANZONE", "CAPANNA", "CAPELLI", "CAPELLO",
  "CARAFFA", "CARBONE", "CARENZA", "CAREZZA", "CARTONE", "CASCATA", "CASELLO", "CASERMA", "CATTIVO", "CAVALLO",
  "CAVERNA", "CAVETTO", "CAVILLO", "CEMENTO", "CERCARE", "CERCHIO", "CIRCOLO", "COLLINA", "COLONNA",
  "COLPIRE", "COMANDO", "CONSOLE", "CONTARE", "COPRIRE", "CORREDO", "CORRERE", "CORTILE", "CORTINA", "COSTUME",
  "CRATERE", "CREDERE", "CRONACA", "CULTURA", "DAVANTI", "DAVVERO", "DEFICIT", "DELFINO", "DESTINO", "DIABETE",
  "DIALOGO", "DINANZI", "DIRETTO", "DIRITTO", "DISCESA", "DISEGNO", "DISPARI", "DIVERSO", "DOCENTE", "DOMANDA",
  "DORMIRE", "DOTTORE", "DRAGONE", "DURANTE", "DUREZZA", "EDICOLA", "EFFETTO", "ELEVARE", "EMPORIO", "ENERGIA",
  "ENTRARE", "ENTRATA", "ESEMPIO", "ESORDIO", "ESPORRE", "ESTREMO", "EUROPEO", "EVITARE", "FALCONE", "FASCINO",
  "FATTORE", "FERMARE", "FIDUCIA", "FIORITO", "FISSARE", "FONDARE", "FORESTA", "FORMARE", "FORMICA", "FORNIRE",
  "FORTUNA", "FRAGILE", "FUGGIRE", "FULMINE", "GENTILE", "GETTARE", "GIOCARE", "GIOVANE", "GIUDICE", "GOVERNO",
  "GRADINO", "GRIDARE", "GUARDIA", "GUIDARE", "IMPORRE", "INFATTI", "INGLESE", "INOLTRE", "INSIEME", "INSOMMA",
  "INTANTO", "INTERNO", "INTORNO", "INUTILE", "INVERNO", "ISTANTE", "LEGGERE", "LEGGERO", "LETTERA", "LIBERTA",
  "LONTANO", "MAESTRO", "MANCARE", "MANDARE", "MANIERA", "MASSIMO", "MATERIA", "MATTINA", "MATTINO", "MEMORIA",
  "MERCATO", "METTERE", "MILIONE", "MODERNO", "MOMENTO", "MUOVERE", "NASCERE", "NAZIONE", "NEANCHE", "NEMMENO",
  "NEPPURE", "NESSUNO", "NORMALE", "NOTIZIA", "OFFRIRE", "OGGETTO", "OPERAIO", "OPPORRE", "ORIGINE", "PADRONE",
  "PALAZZO", "PARLARE", "PARTIRE", "PARTITO", "PASSARE", "PASSATO", "PECCATO", "PENSARE", "PERDERE", "PERFINO",
  "PERIODO", "PERSONA", "PIACERE", "PIANETA", "PIANURA", "PICCOLO", "POLIZIA", "PORTARE", "POTENZA", "PRECISO",
  "PREGARE", "PRIVATO", "PROFUMO", "PROPRIO", "PROVARE", "QUALCHE", "RAGAZZA", "RAGAZZO", "RAGIONE",
  "RECENTE", "REGIONE", "RENDERE", "RESTARE", "RICERCA", "RICORDO", "RIDURRE", "RITORNO", "RIUNIRE", "ROMPERE",
  "SALTARE", "SALVARE", "SCIENZA", "SCRITTO", "SCUSARE", "SECONDO", "SEGNARE", "SEGRETO", "SEGUIRE", "SEGUITO",
  "SENTIRE", "SERVIRE", "SGUARDO", "SIGNORA", "SIGNORE", "SISTEMA", "SOCIALE", "SOCIETA", "SOGNARE", "SOLDATO",
  "SORELLA", "SORGERE", "SORRISO", "SOTTILE", "SPERARE", "SPIRITO", "SPOSARE", "STASERA", "STORICO", "STUPIDO",
  "SUONARE", "TECNICO", "TEDESCO", "TENDERE", "TENTARE", "TERMINE", "TERRENO", "TOCCARE", "TORNARE", "TROVARE",
  "UFFICIO", "VALIGIA", "VECCHIO", "VENDERE", "VESTIRE", "VESTITO", "VIAGGIO", "VINCERE", "VITTORIA", "VOLGARE", "VOLGERE", "VOLTARE", "VORTICE", "ZATTERA", "ZINGARO"
];

const WORDS_POOL_8 = [
  "ABBAGLIO", "ABBIOCCO", "ABBRACCI", "ABBRONZO", "ABITANTE", "ACCADERE", "ACCANITO", "ACCUDITO", "ACCUMULO",
  "ACCURATO", "ACQUARIO", "ACQUISTO", "ACROBATA", "ADEGUATO", "ADERENZA", "ADESIONE", "AFFABILE", "AFFILATO", "AGGIUNTA",
  "AGGIUSTA", "ALBERATO", "ALFABETO", "ALLEGATO", "ALLEGRIA", "ALLENATO", "ALLERGIA", "ALTALENA", "ALTERATO",
  "AMBIENTE", "AMMIRATO", "ANATOMIA", "ANDATURA", "ANEDDOTO", "ANGELICO", "ANGOLARE", "ANGOSCIA", "ANTENATO",
  "ANTIDOTO", "APERTURA", "APOSTOLO", "APPAGATO", "APPARATO", "APPARIRE", "APPETITO", "AQUILONE", "ARAGOSTA",
  "ARCHIVIO", "ARGENTEO", "ARMONICO", "ARREDATO", "ARRIVARE", "ARRIVATO", "ARTICOLO", "ASPARAGO", "ASSETATO", "ASSICURA",
  "ASSOLUTO", "ASSUMERE", "ASTRATTO", "ATTEGGIA", "AUTONOMO", "AVANZARE", "AVANZATA", "AVVENIRE", "AVVOCATO", "BAGAGLIO", "BAGNANTE", "BALLETTO", "BANCOMAT", "BANDIERA", "BARBIERE",
  "BATTERIA", "BATTEZZO", "BELLEZZA", "BENFATTO", "BILANCIA", "BIOLOGIA", "BOCCETTA", "BORGHESE", "BOTTIGLIA", "BOZZETTO",
  "BRUCIARE", "BURRASCA", "CALAMITA", "CAMBIARE", "CAMPAGNA", "CAMPIONE", "CANTIERE", "CAPITALE", "CAPITANO",
  "CAPITARE", "CAPRICCI", "CARRELLO", "CARRIERA", "CASTAGNA", "CENTRALE", "CERAMICA", "CERVELLO", "CHIAMARE",
  "CHIEDERE", "CHITARRA", "CHIUDERE", "CIABATTA", "CIASCUNO", "CILIEGIO", "CINQUINA", "COMPAGNO", "COMPIERE", "COMPORRE",
  "COMPRARE", "COMPUTER", "COMUNQUE", "CONCERTO", "CONCETTO", "CONDOTTA", "CONDURRE", "CONTATTO", "CONTENTO", "CONTINUO",
  "CORAGGIO", "CORRENTE", "COSTANZA", "CREATIVO", "CRESCERE", "CUSTODIA", "DECIDERE", "DEDICARE", "DELICATO", "DEPOSITO",
  "DINAMICA", "DIRIGERE", "DISCORSO", "DISPORRE", "DISTANZA", "DIVENIRE", "DIVIDERE", "DOLCEZZA", "DOMENICA",
  "ECCETERA", "ELEFANTE", "ELEGANZA", "ELEMENTO", "ESERCITO", "ESISTERE", "ESPRESSO", "FABBRICA", "FAMIGLIA", "FANTASIA",
  "FENOMENO", "FERROVIA", "FIGURARE", "FINESTRA", "FOGLIAME", "FRANCESE", "FRATELLO", "FUNZIONE", "GENERALE",
  "GIARDINI", "GIARDINO", "GIORNALE", "GIORNATA", "GIRASOLE", "GIUDIZIO", "GIUNGERE", "GUARDARE", "IMMAGINE", "IMPARARE",
  "IMPEDIRE", "INDICARE", "INDIETRO", "INIZIARE", "INSONNIA", "INVITARE", "ISTITUTO", "ITALIANO", "LANCIARE", "LANTERNA",
  "LASCIARE", "LAVORARE", "LIBERARE", "LIMITARE", "MACCHINA", "MAESTOSO", "MAGGIORE", "MALATTIA", "MANGIARE", "MEDESIMO",
  "MERITARE", "MESTIERE", "MIGLIORE", "MILITARE", "MINISTRO", "MONTAGNA", "MOSTRARE", "NATURALE", "NOTEVOLE", "NUMEROSO",
  "OFFICINA", "OPINIONE", "ORDINARE", "ORECCHIO", "ORIZZONTE", "OROLOGIO", "OSPEDALE", "OTTENERE", "PANORAMA", "PASSIONE",
  "PENSIERO", "PERFETTO", "PERICOLO", "PIANGERE", "PIANTARE", "POLITICA", "POLITICO", "PRENDERE", "PRESENTE", "PRESENZA",
  "PRINCIPE", "PROBLEMA", "PROCESSO", "PRODOTTO", "PRODURRE", "PROFONDO", "PROPORRE", "PROPOSTA", "PROSSIMO", "PUBBLICO",
  "QUALCOSA", "QUALCUNO", "RACCONTO", "RAPPORTO", "RICEVERE", "RIEMPIRE", "RIFERIRE", "RIMANERE", "RIPETERE", "RISPETTO",
  "RISPOSTA", "RITENERE", "RIUSCIRE", "RIVEDERE", "RIVELARE", "SALUTARE", "SCAPPARE", "SCENDERE", "SCOPRIRE", "SCORRERE",
  "SCRIVERE", "SEMBRARE", "SEMPLICE", "SENTIERO", "SERENITA", "SERVIZIO", "SILENZIO", "SIMPATIA", "SINISTRO", "SMETTERE",
  "SOFFRIRE", "SOLTANTO", "SPECCHIO", "SPECIALE", "SPEGNERE", "SPERANZA", "SPIEGARE", "SPINGERE", "SPLENDORE", "STACCARE",
  "STAGIONE", "STAZIONE", "STELLATO", "STUDIARE", "SUCCESSO", "SUPERARE", "SVILUPPO", "SVOLGERE", "TAGLIARE", "TEMPORALE",
  "TOGLIERE", "TRADIZIONE", "TRATTARE", "TUTTAVIA", "UCCIDERE", "UNIVERSO", "ZAMPOGNA", "ZUCCHERO"
];

// Generatore PRNG deterministico a 32-bit (Mulberry32) ad alta uniforme distribuzione
function createPseudoRandom(seed) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Estrazione deterministica delle 5 parole giornaliere (1 per ciascun round)
function getDailyPuzzle(customDayNumber = null) {
  let dayNumber = customDayNumber;

  if (!dayNumber) {
    const startDate = new Date("2026-01-01T00:00:00");
    const now = new Date();
    const diffTime = Math.abs(now.getTime() - startDate.getTime());
    dayNumber = Math.floor(diffTime / (1000 * 60 * 60 * 24)) + 1;
  }

  // Seed differenziati con numeri primi per evitare qualsiasi correlazione tra i round
  const rng4 = createPseudoRandom((dayNumber * 73856093) ^ 0x9e3779b9);
  const rng5 = createPseudoRandom((dayNumber * 19349663) ^ 0x85ebca6b);
  const rng6 = createPseudoRandom((dayNumber * 83492791) ^ 0xc2b2ae35);
  const rng7 = createPseudoRandom((dayNumber * 29712150) ^ 0x27d4eb2f);
  const rng8 = createPseudoRandom((dayNumber * 98245165) ^ 0x165667b1);

  const word4 = WORDS_POOL_4[Math.floor(rng4() * WORDS_POOL_4.length)];
  const word5 = WORDS_POOL_5[Math.floor(rng5() * WORDS_POOL_5.length)];
  const word6 = WORDS_POOL_6[Math.floor(rng6() * WORDS_POOL_6.length)];
  const word7 = WORDS_POOL_7[Math.floor(rng7() * WORDS_POOL_7.length)];
  const word8 = WORDS_POOL_8[Math.floor(rng8() * WORDS_POOL_8.length)];

  return {
    dayNumber: dayNumber,
    words: [word4, word5, word6, word7, word8]
  };
}

// Mescolamento deterministico Fisher-Yates per la griglia comune di 30 tessere
function shuffleArrayWithSeed(array, seed) {
  const arr = [...array];
  const rng = createPseudoRandom(seed);
  let m = arr.length;
  let t, i;

  while (m) {
    i = Math.floor(rng() * m--);
    t = arr[m];
    arr[m] = arr[i];
    arr[i] = t;
  }

  return arr;
}